Double-sided arrows added
Within an existing training reaction for the Disproportionation family
the reaction label was changed from "C2H3 + O2 = C2H2_1 + HO2" to
"C2H3 + O2 <=> C2H2_1 + HO2", so that reaction.label = str(reaction.item)
and the error:

rmgpy.data.kinetics.common.KineticsError: Reactions are now defined
 solely by their labels, but reaction C2H3 + O2 <=> C2H2_1 + HO2
 has label 'C2H3 + O2 = C2H2_1 + HO2'

is no longer thrown when saving the database.