When running 'kineticsGroups.py generate' don't have test sets.
Having them causes it to die as follows:

Traceback (most recent call last):
  File "kineticsGroups.py", line 431, in <module>
    args.run(args, database)
  File "kineticsGroups.py", line 386, in generate
    plot = False,
  File "kineticsGroups.py", line 187, in generateKineticsGroupValues
    for entry in database.kinetics.depository['{0}/{1}'.format(family,label)].entries.values():
KeyError: 'Intra_R_Add_Exocyclic/PrIMe'

Removing them fixes it.