C -> C2s in 1+2 cyclo add groups to prevent atomtype error
changing to C2s prevents matching of C2sc groups which raise atomtype error when template is applied:
Error: Could not update atomtypes for this molecule:
multiplicity -187
1    F u0 p3 c0 {4,S}
2    O u0 p1 c+1 {3,D} {4,S}
3    O u0 p2 c0 {2,D}
4 *3 C u0 p0 c-1 {1,S} {2,S} {5,S} {6,S} {8,S}
5    H u0 p0 c0 {4,S}
6 *2 O u0 p2 c0 {4,S} {8,S}
7    O u0 p2 c0 {8,D}
8 *1 C u0 p0 c0 {4,S} {6,S} {7,D}

Error: Problem family: 1+2_Cycloaddition
Error: Problem reactants: (Molecule(smiles="O=C=O"), Molecule(smiles="O=[O+][C-]F"))
Error: <Molecule "O=C=O">
1 *2 O u0 p2 c0 {3,D}
2    O u0 p2 c0 {3,D}
3 *1 C u0 p0 c0 {1,D} {2,D}

Error: <Molecule "O=[O+][C-]F">
1    F u0 p3 c0 {4,S}
2    O u0 p1 c+1 {3,D} {4,S}
3    O u0 p2 c0 {2,D}
4 *3 C u0 p1 c-1 {1,S} {2,S} {5,S}
5    H u0 p0 c0 {4,S}