removed spaces in Cyclic Ether Formation dictionary which cause read error
this should avoid the following error during RMG database reading:
Reading forward template:   Cyclic_Ether_Formation
ERROR: Error on line: 1 *1 {Cd,Cs,CO, Sid,Sis} 1 {2,{S,D}}
Error in read in reaction template: Cyclic_Ether_Formation
R2OOH: free electron: Sid,Sis}